name: Convert RNC to RNG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Apply patch to submodule
        run: |
          bash scripts/apply-patch.sh

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Convert
        run: |
          bash scripts/convert.sh

      - name: Commit and push generated RNG files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add generated-schemas/

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-convert RNC to RNG in generated-schemas/"
            git push
          fi
